server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ArmeniaBank
      client:
        registration:
          auth-service:
            provider: keycloak
            client-id: auth-service
            client-secret: auth-service
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/swagger-ui/oauth2-redirect.html"
            client-name: Swagger UI
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ArmeniaBank

  datasource:
    url: jdbc:postgresql://postgres:5432/auth_service
    username: auth_service
    password: auth_service
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      password: auth_service
      timeout: 60000

  liquibase:
    change-log: classpath:/db/migration/changelog.xml
    default-schema: auth_service
    clear-checksums: true

  mail:
    host: smtp.gmail.com
    username: armeniabank25@gmail.com
    password: xukgxkpjyeqpanry
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:8081/swagger-ui/oauth2-redirect.html
    use-root-path: true
    oauth:
      client-id: auth-service
      client-secret: auth-service
      use-pkce-with-authorization-code-grant: true

  api-docs:
    path: /v3/api-docs

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

kafka:
  topic:
    auth-events: auth-events

audit-service:
  url: http://audit-service:8082


keycloak:
  base-url: http://backend-keycloak-auth:8080
  token-uri: /realms/ArmeniaBank/protocol/openid-connect/token
  realm: ArmeniaBank
  client-id: auth-service
  client-secret: auth-service

logging:
  config: classpath:/logback-spring.xml
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

app:
  verification-url: http://localhost:8081/api/verify/email

user:
  verification:
    picture:
      path: D:\Test_Task\Armenia_Bank\document