server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit-service
    username: audit-service
    password: audit-service
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/migration/changelog.xml
    clear-checksums: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

kafka:
  topic:
    audit-events: audit-events

audit-service:
  base-url: http://audit-service:8082

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG