server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_service
    username: audit_service
    password: audit_service
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/migration/changelog.xml
    clear-checksums: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    audit-events: audit-events

archive:
  audit: D:/Test_Task/Armenia_Bank/archive/audit_

audit-service:
  base-url: http://audit-service:8082

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka.clients.consumer: DEBUG